apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-response-interceptor-streaming
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-response-interceptor-streaming
    app.kubernetes.io/part-of: quarkus-response-interceptor-streaming
  name: quarkus-response-interceptor-streaming
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quarkus-response-interceptor-streaming
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quarkus-response-interceptor-streaming
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-it-pajennin-tenant/quarkus-response-interceptor-streaming/quarkus-response-interceptor-streaming@sha256:07bb9b52cf35bb52edea2a295f537ec51b99fe1dee12bd7f80590611d4daa25a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
