apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-response-interceptor-streaming
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-response-interceptor-streaming
    app.kubernetes.io/part-of: quarkus-response-interceptor-streaming
  name: quarkus-response-interceptor-streaming
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: quarkus-response-interceptor-streaming
status:
  loadBalancer: {}
